site_name: VLDocking library
repo_url: https://github.com/omegat-org/vldocking
docs_dir: wiki
nav:
  - 1. Getting started: 'tutorial1.md'
  - 1a. And now... Docking!: 'tutorial1page2.md'
  - 2. Customizing layout: 'tutorial2.md'
  - 3. Events: 'tutorial3.md'
  - 4. Workspaces: 'tutorial4.md'
  - 5. Extending VLDocking: 'tutorial5.md'
  - 6. Tips & Tricks: 'tutorial6.md'
  - 7. Heavyweight components: 'tutorial7.md'
  - 8. Customizing the UI: 'tutorial8.md'
  - 9. Toolbars: 'tutorial9.md'
  - 10. Compound dockables: 'tutorial10.md'
  - 11. Multi-desktop applications: 'tutorial11.md'
  - 12. Anchored dockables: 'tutorial12.md'

theme:
  name: material
  features:
  - navigation.tracking
  - navigation.top
  - content.code.copy

markdown_extensions:
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html